[tool.poetry]
name = "alabarym_brain_games"
version = "0.1.0"
description = ""
authors = ["alabarym"]
packages = [
  { include = "brain_games"  },
  
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
